image: registry.cloud.fits/fits/buildtools:1

stages:
  - build
variables:
  BLOBSTORE_URL: https://blobstore.fi-ts.io
  GOOGLE_BUCKETS: https://storage.googleapis.com
  GOOGLE_IMAGES_BUCKET: images.metal-stack.io

before_script:
  - mc config host add fits ${BLOBSTORE_URL} ${BLOB_ACCESS_KEY} "${BLOB_SECRET_KEY}"
  - mc config host add google ${GOOGLE_BUCKETS} ${GOOGLE_ACCESS_KEY} "${GOOGLE_SECRET_KEY}"
  - docker-make --no-push --Lint
  - md5sum metal-hammer-initrd.img.lz4 > metal-hammer-initrd.img.lz4.md5
  - mkdir -p images/metal-hammer
after_script:
  - mc cp --recursive images fits/metal
  - mc cp --recursive images/metal-hammer google/${GOOGLE_IMAGES_BUCKET}

metal-hammer-master:
  stage: build
  script:
    - mv metal-hammer-initrd.img.lz4* images/metal-hammer/
  only:
    - master

metal-hammer-tag-or-branch:
  stage: build
  script:
    - mkdir -p images/metal-hammer/${CI_COMMIT_REF_NAME}
    - mv metal-hammer-initrd.img.lz4* images/metal-hammer/${CI_COMMIT_REF_NAME}/
  except:
    - master
